/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro.entity;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class address extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3402012862362299864L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"address\",\"namespace\":\"com.example.avro.entity\",\"fields\":[{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"suite\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"zipcode\",\"type\":\"string\"},{\"name\":\"geo\",\"type\":{\"type\":\"record\",\"name\":\"geo\",\"fields\":[{\"name\":\"lat\",\"type\":\"string\"},{\"name\":\"lng\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<address> ENCODER =
      new BinaryMessageEncoder<address>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<address> DECODER =
      new BinaryMessageDecoder<address>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<address> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<address> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<address> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<address>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this address to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a address from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a address instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static address fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence street;
   private java.lang.CharSequence suite;
   private java.lang.CharSequence city;
   private java.lang.CharSequence zipcode;
   private com.example.avro.entity.geo geo;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public address() {}

  /**
   * All-args constructor.
   * @param street The new value for street
   * @param suite The new value for suite
   * @param city The new value for city
   * @param zipcode The new value for zipcode
   * @param geo The new value for geo
   */
  public address(java.lang.CharSequence street, java.lang.CharSequence suite, java.lang.CharSequence city, java.lang.CharSequence zipcode, com.example.avro.entity.geo geo) {
    this.street = street;
    this.suite = suite;
    this.city = city;
    this.zipcode = zipcode;
    this.geo = geo;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return street;
    case 1: return suite;
    case 2: return city;
    case 3: return zipcode;
    case 4: return geo;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: street = (java.lang.CharSequence)value$; break;
    case 1: suite = (java.lang.CharSequence)value$; break;
    case 2: city = (java.lang.CharSequence)value$; break;
    case 3: zipcode = (java.lang.CharSequence)value$; break;
    case 4: geo = (com.example.avro.entity.geo)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'street' field.
   * @return The value of the 'street' field.
   */
  public java.lang.CharSequence getStreet() {
    return street;
  }


  /**
   * Sets the value of the 'street' field.
   * @param value the value to set.
   */
  public void setStreet(java.lang.CharSequence value) {
    this.street = value;
  }

  /**
   * Gets the value of the 'suite' field.
   * @return The value of the 'suite' field.
   */
  public java.lang.CharSequence getSuite() {
    return suite;
  }


  /**
   * Sets the value of the 'suite' field.
   * @param value the value to set.
   */
  public void setSuite(java.lang.CharSequence value) {
    this.suite = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'zipcode' field.
   * @return The value of the 'zipcode' field.
   */
  public java.lang.CharSequence getZipcode() {
    return zipcode;
  }


  /**
   * Sets the value of the 'zipcode' field.
   * @param value the value to set.
   */
  public void setZipcode(java.lang.CharSequence value) {
    this.zipcode = value;
  }

  /**
   * Gets the value of the 'geo' field.
   * @return The value of the 'geo' field.
   */
  public com.example.avro.entity.geo getGeo() {
    return geo;
  }


  /**
   * Sets the value of the 'geo' field.
   * @param value the value to set.
   */
  public void setGeo(com.example.avro.entity.geo value) {
    this.geo = value;
  }

  /**
   * Creates a new address RecordBuilder.
   * @return A new address RecordBuilder
   */
  public static com.example.avro.entity.address.Builder newBuilder() {
    return new com.example.avro.entity.address.Builder();
  }

  /**
   * Creates a new address RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new address RecordBuilder
   */
  public static com.example.avro.entity.address.Builder newBuilder(com.example.avro.entity.address.Builder other) {
    if (other == null) {
      return new com.example.avro.entity.address.Builder();
    } else {
      return new com.example.avro.entity.address.Builder(other);
    }
  }

  /**
   * Creates a new address RecordBuilder by copying an existing address instance.
   * @param other The existing instance to copy.
   * @return A new address RecordBuilder
   */
  public static com.example.avro.entity.address.Builder newBuilder(com.example.avro.entity.address other) {
    if (other == null) {
      return new com.example.avro.entity.address.Builder();
    } else {
      return new com.example.avro.entity.address.Builder(other);
    }
  }

  /**
   * RecordBuilder for address instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<address>
    implements org.apache.avro.data.RecordBuilder<address> {

    private java.lang.CharSequence street;
    private java.lang.CharSequence suite;
    private java.lang.CharSequence city;
    private java.lang.CharSequence zipcode;
    private com.example.avro.entity.geo geo;
    private com.example.avro.entity.geo.Builder geoBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.avro.entity.address.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.street)) {
        this.street = data().deepCopy(fields()[0].schema(), other.street);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.suite)) {
        this.suite = data().deepCopy(fields()[1].schema(), other.suite);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.city)) {
        this.city = data().deepCopy(fields()[2].schema(), other.city);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.zipcode)) {
        this.zipcode = data().deepCopy(fields()[3].schema(), other.zipcode);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.geo)) {
        this.geo = data().deepCopy(fields()[4].schema(), other.geo);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasGeoBuilder()) {
        this.geoBuilder = com.example.avro.entity.geo.newBuilder(other.getGeoBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing address instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.avro.entity.address other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.street)) {
        this.street = data().deepCopy(fields()[0].schema(), other.street);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.suite)) {
        this.suite = data().deepCopy(fields()[1].schema(), other.suite);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.city)) {
        this.city = data().deepCopy(fields()[2].schema(), other.city);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.zipcode)) {
        this.zipcode = data().deepCopy(fields()[3].schema(), other.zipcode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.geo)) {
        this.geo = data().deepCopy(fields()[4].schema(), other.geo);
        fieldSetFlags()[4] = true;
      }
      this.geoBuilder = null;
    }

    /**
      * Gets the value of the 'street' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreet() {
      return street;
    }


    /**
      * Sets the value of the 'street' field.
      * @param value The value of 'street'.
      * @return This builder.
      */
    public com.example.avro.entity.address.Builder setStreet(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.street = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'street' field has been set.
      * @return True if the 'street' field has been set, false otherwise.
      */
    public boolean hasStreet() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'street' field.
      * @return This builder.
      */
    public com.example.avro.entity.address.Builder clearStreet() {
      street = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'suite' field.
      * @return The value.
      */
    public java.lang.CharSequence getSuite() {
      return suite;
    }


    /**
      * Sets the value of the 'suite' field.
      * @param value The value of 'suite'.
      * @return This builder.
      */
    public com.example.avro.entity.address.Builder setSuite(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.suite = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'suite' field has been set.
      * @return True if the 'suite' field has been set, false otherwise.
      */
    public boolean hasSuite() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'suite' field.
      * @return This builder.
      */
    public com.example.avro.entity.address.Builder clearSuite() {
      suite = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public com.example.avro.entity.address.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.city = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public com.example.avro.entity.address.Builder clearCity() {
      city = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'zipcode' field.
      * @return The value.
      */
    public java.lang.CharSequence getZipcode() {
      return zipcode;
    }


    /**
      * Sets the value of the 'zipcode' field.
      * @param value The value of 'zipcode'.
      * @return This builder.
      */
    public com.example.avro.entity.address.Builder setZipcode(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.zipcode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'zipcode' field has been set.
      * @return True if the 'zipcode' field has been set, false otherwise.
      */
    public boolean hasZipcode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'zipcode' field.
      * @return This builder.
      */
    public com.example.avro.entity.address.Builder clearZipcode() {
      zipcode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'geo' field.
      * @return The value.
      */
    public com.example.avro.entity.geo getGeo() {
      return geo;
    }


    /**
      * Sets the value of the 'geo' field.
      * @param value The value of 'geo'.
      * @return This builder.
      */
    public com.example.avro.entity.address.Builder setGeo(com.example.avro.entity.geo value) {
      validate(fields()[4], value);
      this.geoBuilder = null;
      this.geo = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'geo' field has been set.
      * @return True if the 'geo' field has been set, false otherwise.
      */
    public boolean hasGeo() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'geo' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.example.avro.entity.geo.Builder getGeoBuilder() {
      if (geoBuilder == null) {
        if (hasGeo()) {
          setGeoBuilder(com.example.avro.entity.geo.newBuilder(geo));
        } else {
          setGeoBuilder(com.example.avro.entity.geo.newBuilder());
        }
      }
      return geoBuilder;
    }

    /**
     * Sets the Builder instance for the 'geo' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.avro.entity.address.Builder setGeoBuilder(com.example.avro.entity.geo.Builder value) {
      clearGeo();
      geoBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'geo' field has an active Builder instance
     * @return True if the 'geo' field has an active Builder instance
     */
    public boolean hasGeoBuilder() {
      return geoBuilder != null;
    }

    /**
      * Clears the value of the 'geo' field.
      * @return This builder.
      */
    public com.example.avro.entity.address.Builder clearGeo() {
      geo = null;
      geoBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public address build() {
      try {
        address record = new address();
        record.street = fieldSetFlags()[0] ? this.street : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.suite = fieldSetFlags()[1] ? this.suite : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.city = fieldSetFlags()[2] ? this.city : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.zipcode = fieldSetFlags()[3] ? this.zipcode : (java.lang.CharSequence) defaultValue(fields()[3]);
        if (geoBuilder != null) {
          try {
            record.geo = this.geoBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("geo"));
            throw e;
          }
        } else {
          record.geo = fieldSetFlags()[4] ? this.geo : (com.example.avro.entity.geo) defaultValue(fields()[4]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<address>
    WRITER$ = (org.apache.avro.io.DatumWriter<address>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<address>
    READER$ = (org.apache.avro.io.DatumReader<address>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.street);

    out.writeString(this.suite);

    out.writeString(this.city);

    out.writeString(this.zipcode);

    this.geo.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.street = in.readString(this.street instanceof Utf8 ? (Utf8)this.street : null);

      this.suite = in.readString(this.suite instanceof Utf8 ? (Utf8)this.suite : null);

      this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);

      this.zipcode = in.readString(this.zipcode instanceof Utf8 ? (Utf8)this.zipcode : null);

      if (this.geo == null) {
        this.geo = new com.example.avro.entity.geo();
      }
      this.geo.customDecode(in);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.street = in.readString(this.street instanceof Utf8 ? (Utf8)this.street : null);
          break;

        case 1:
          this.suite = in.readString(this.suite instanceof Utf8 ? (Utf8)this.suite : null);
          break;

        case 2:
          this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);
          break;

        case 3:
          this.zipcode = in.readString(this.zipcode instanceof Utf8 ? (Utf8)this.zipcode : null);
          break;

        case 4:
          if (this.geo == null) {
            this.geo = new com.example.avro.entity.geo();
          }
          this.geo.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










