/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro.entity;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class company extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3204312626510651516L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"company\",\"namespace\":\"com.example.avro.entity\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"catchPhrase\",\"type\":\"string\"},{\"name\":\"bs\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<company> ENCODER =
      new BinaryMessageEncoder<company>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<company> DECODER =
      new BinaryMessageDecoder<company>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<company> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<company> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<company> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<company>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this company to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a company from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a company instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static company fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence name;
   private java.lang.CharSequence catchPhrase;
   private java.lang.CharSequence bs;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public company() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param catchPhrase The new value for catchPhrase
   * @param bs The new value for bs
   */
  public company(java.lang.CharSequence name, java.lang.CharSequence catchPhrase, java.lang.CharSequence bs) {
    this.name = name;
    this.catchPhrase = catchPhrase;
    this.bs = bs;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return catchPhrase;
    case 2: return bs;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: catchPhrase = (java.lang.CharSequence)value$; break;
    case 2: bs = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'catchPhrase' field.
   * @return The value of the 'catchPhrase' field.
   */
  public java.lang.CharSequence getCatchPhrase() {
    return catchPhrase;
  }


  /**
   * Sets the value of the 'catchPhrase' field.
   * @param value the value to set.
   */
  public void setCatchPhrase(java.lang.CharSequence value) {
    this.catchPhrase = value;
  }

  /**
   * Gets the value of the 'bs' field.
   * @return The value of the 'bs' field.
   */
  public java.lang.CharSequence getBs() {
    return bs;
  }


  /**
   * Sets the value of the 'bs' field.
   * @param value the value to set.
   */
  public void setBs(java.lang.CharSequence value) {
    this.bs = value;
  }

  /**
   * Creates a new company RecordBuilder.
   * @return A new company RecordBuilder
   */
  public static com.example.avro.entity.company.Builder newBuilder() {
    return new com.example.avro.entity.company.Builder();
  }

  /**
   * Creates a new company RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new company RecordBuilder
   */
  public static com.example.avro.entity.company.Builder newBuilder(com.example.avro.entity.company.Builder other) {
    if (other == null) {
      return new com.example.avro.entity.company.Builder();
    } else {
      return new com.example.avro.entity.company.Builder(other);
    }
  }

  /**
   * Creates a new company RecordBuilder by copying an existing company instance.
   * @param other The existing instance to copy.
   * @return A new company RecordBuilder
   */
  public static com.example.avro.entity.company.Builder newBuilder(com.example.avro.entity.company other) {
    if (other == null) {
      return new com.example.avro.entity.company.Builder();
    } else {
      return new com.example.avro.entity.company.Builder(other);
    }
  }

  /**
   * RecordBuilder for company instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<company>
    implements org.apache.avro.data.RecordBuilder<company> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence catchPhrase;
    private java.lang.CharSequence bs;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.avro.entity.company.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.catchPhrase)) {
        this.catchPhrase = data().deepCopy(fields()[1].schema(), other.catchPhrase);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.bs)) {
        this.bs = data().deepCopy(fields()[2].schema(), other.bs);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing company instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.avro.entity.company other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.catchPhrase)) {
        this.catchPhrase = data().deepCopy(fields()[1].schema(), other.catchPhrase);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bs)) {
        this.bs = data().deepCopy(fields()[2].schema(), other.bs);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.example.avro.entity.company.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.example.avro.entity.company.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'catchPhrase' field.
      * @return The value.
      */
    public java.lang.CharSequence getCatchPhrase() {
      return catchPhrase;
    }


    /**
      * Sets the value of the 'catchPhrase' field.
      * @param value The value of 'catchPhrase'.
      * @return This builder.
      */
    public com.example.avro.entity.company.Builder setCatchPhrase(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.catchPhrase = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'catchPhrase' field has been set.
      * @return True if the 'catchPhrase' field has been set, false otherwise.
      */
    public boolean hasCatchPhrase() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'catchPhrase' field.
      * @return This builder.
      */
    public com.example.avro.entity.company.Builder clearCatchPhrase() {
      catchPhrase = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'bs' field.
      * @return The value.
      */
    public java.lang.CharSequence getBs() {
      return bs;
    }


    /**
      * Sets the value of the 'bs' field.
      * @param value The value of 'bs'.
      * @return This builder.
      */
    public com.example.avro.entity.company.Builder setBs(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.bs = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'bs' field has been set.
      * @return True if the 'bs' field has been set, false otherwise.
      */
    public boolean hasBs() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'bs' field.
      * @return This builder.
      */
    public com.example.avro.entity.company.Builder clearBs() {
      bs = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public company build() {
      try {
        company record = new company();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.catchPhrase = fieldSetFlags()[1] ? this.catchPhrase : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.bs = fieldSetFlags()[2] ? this.bs : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<company>
    WRITER$ = (org.apache.avro.io.DatumWriter<company>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<company>
    READER$ = (org.apache.avro.io.DatumReader<company>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.catchPhrase);

    out.writeString(this.bs);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.catchPhrase = in.readString(this.catchPhrase instanceof Utf8 ? (Utf8)this.catchPhrase : null);

      this.bs = in.readString(this.bs instanceof Utf8 ? (Utf8)this.bs : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.catchPhrase = in.readString(this.catchPhrase instanceof Utf8 ? (Utf8)this.catchPhrase : null);
          break;

        case 2:
          this.bs = in.readString(this.bs instanceof Utf8 ? (Utf8)this.bs : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










